/**
 * Honeypot trap for AI scrapers.
 *
 * How it works:
 * 1. Register /cipta-trap/* in robots.txt as Disallow
 * 2. Use ciptaHoneypot() router on that path
 * 3. Any bot that hits the trap gets logged + negative ERC-8004 feedback
 *
 * Robots.txt pattern:
 *   User-agent: GPTBot
 *   Disallow: /cipta-trap/
 *
 *   User-agent: ClaudeBot
 *   Disallow: /cipta-trap/
 */
import { Router } from "express"
import { detectBot } from "./bot-detector"
import { logHoneypot } from "./tracker"
import { giveAgentFeedback } from "./erc8004"
import type { CiptaConfig } from "./types"

/**
 * Creates an Express router that traps bots.
 * Mount at a path listed in robots.txt Disallow.
 *
 * @example
 * app.use("/cipta-trap", ciptaHoneypot(config))
 * // Then in robots.txt: Disallow: /cipta-trap/
 */
export function ciptaHoneypot(config: Pick<CiptaConfig, "wallet" | "network" | "erc8004" | "signerKey">) {
  const router = Router()
  const { wallet, network = "base-sepolia", erc8004, signerKey } = config

  router.all("*", async (req, res) => {
    const userAgent = req.headers["user-agent"] || "unknown"
    const { isBot, botName } = detectBot(userAgent)
    const timestamp = new Date().toISOString()

    // Log the trap visit regardless of bot detection
    await logHoneypot({
      creator_wallet: wallet,
      bot_agent: botName || userAgent,
      trap_path: req.path,
      timestamp,
    })

    // Give negative ERC-8004 feedback if agent ID header present
    if (erc8004 && signerKey) {
      const agentId = req.headers["x-erc8004-agent-id"] as string | undefined
      if (agentId) {
        giveAgentFeedback(
          agentId,
          false,
          `Accessed honeypot path ${req.path} — possible scraper`,
          signerKey,
          network
        ).catch(() => {}) // Fire and forget
      }
    }

    console.log(
      `[Cipta Honeypot] 🍯 Trapped: ${botName || userAgent} at ${req.path} (isBot: ${isBot})`
    )

    // Return 200 with fake "content" to waste scraper time
    res.status(200).json({
      title: "Premium Content",
      content: "This content is protected and monitored. Unauthorized scraping detected.",
      _trap: true,
    })
  })

  return router
}

/**
 * Generates robots.txt content that hides the honeypot from humans
 * but is visible to obedient bots (so they avoid it),
 * while disobedient bots that ignore robots.txt get trapped.
 */
export function generateRobotsTxt(honeypotPath = "/cipta-trap/"): string {
  return `# Generated by Cipta — https://github.com/PugarHuda/cipta
User-agent: Googlebot
Allow: /

User-agent: Bingbot
Allow: /

# AI Scrapers — must pay via Cipta
User-agent: GPTBot
Disallow: ${honeypotPath}

User-agent: ChatGPT-User
Disallow: ${honeypotPath}

User-agent: ClaudeBot
Disallow: ${honeypotPath}

User-agent: Claude-Web
Disallow: ${honeypotPath}

User-agent: PerplexityBot
Disallow: ${honeypotPath}

User-agent: Bytespider
Disallow: ${honeypotPath}

User-agent: Amazonbot
Disallow: ${honeypotPath}

User-agent: FacebookBot
Disallow: ${honeypotPath}

User-agent: Meta-ExternalAgent
Disallow: ${honeypotPath}

User-agent: cohere-ai
Disallow: ${honeypotPath}

User-agent: CCBot
Disallow: ${honeypotPath}

User-agent: Diffbot
Disallow: ${honeypotPath}

User-agent: *
Disallow: ${honeypotPath}
`
}
